import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { auth } from './firebase';
import { signInWithEmailAndPassword } from 'firebase/auth';

function Login() {
  const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
      const [error, setError] = useState('');
        const navigate = useNavigate();

          const handleLogin = async (e) => {
              e.preventDefault();
                  try {
                        await signInWithEmailAndPassword(auth, email, password);
                              navigate('/dashboard');
                                  } catch (error) {
                                        setError('Correo o contraseña incorrectos.');
                                            }
                                              };

                                                return (
                                                    <div
                                                          className="min-h-screen flex items-center justify-center bg-cover bg-center"
                                                                style={{ backgroundImage: `url('/login-bg.jpg')` }}
                                                                    >
                                                                          <div className="bg-white bg-opacity-80 p-8 rounded-lg shadow-lg max-w-sm w-full">
                                                                                  <h2 className="text-2xl font-bold text-center mb-4">Iniciar Sesión</h2>
                                                                                          <form onSubmit={handleLogin}>
                                                                                                    <input
                                                                                                                type="email"
                                                                                                                            placeholder="Correo electrónico"
                                                                                                                                        value={email}
                                                                                                                                                    onChange={(e) => setEmail(e.target.value)}
                                                                                                                                                                className="w-full p-2 mb-4 border rounded"
                                                                                                                                                                            required
                                                                                                                                                                                      />
                                                                                                                                                                                                <input
                                                                                                                                                                                                            type="password"
                                                                                                                                                                                                                        placeholder="Contraseña"
                                                                                                                                                                                                                                    value={password}
                                                                                                                                                                                                                                                onChange={(e) => setPassword(e.target.value)}
                                                                                                                                                                                                                                                            className="w-full p-2 mb-4 border rounded"
                                                                                                                                                                                                                                                                        required
                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                            {error && <p className="text-red-500 text-sm mb-4">{error}</p>}
                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                  type="submit"
                                                                                                                                                                                                                                                                                                                              className="w-full bg-purple-600 text-white p-2 rounded hover:bg-purple-700"
                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                    Entrar
                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                      </form>
                                                                                                                                                                                                                                                                                                                                                                              <p className="mt-4 text-sm text-center">
                                                                                                                                                                                                                                                                                                                                                                                        ¿No tienes cuenta?{' '}
                                                                                                                                                                                                                                                                                                                                                                                                  <span
                                                                                                                                                                                                                                                                                                                                                                                                              onClick={() => navigate('/register')}
                                                                                                                                                                                                                                                                                                                                                                                                                          className="text-purple-700 font-semibold cursor-pointer hover:underline"
                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                Regístrate
                                                                                                                                                                                                                                                                                                                                                                                                                                                          </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                              export default Login;